name: 'SBOM enrichment'
description: 'Adds information to SBOM components and removes unused dependencies'

inputs:
  database:
    description: 'JSON based enrichment data base'
    required: true
    default: 'enrichment_database.json'
  sbom:
    description: 'Input SBOM in CycloneDX JSON format, will be overwritten unless sbom_out is set'
    required: true
    default: 'sbom.cdx.json'
  sbom_out:
    description: 'The updated SBOM will be written here'
    required: false
    default: ''
  cmake_build_dir:
    description: 'The CMake build directory'
    required: false
    default: ''
  msproj_file:
    description: 'MSProj project file'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Get the SBOM enrichment tool
      uses: actions/checkout@v7
      with:
        repository: CommonplaceRobotics/SW_SBOM_Enrichment
        path: sbom_tool

    - name: Install poetry
      shell: bash
      run: |
        pip install poetry

    - name: Install dependencies
      shell: bash
      run: |
        cd sbom_tool
        poetry install --no-root

    - name: Enrich SBOM
      shell: bash
      run: |
        chmod +x sbom_tool/SbomEnrichment.py

        if [ "${{ inputs.sbom_out }}" != "" ]; then
          PARAM_SBOM_OUT="--out ${{ inputs.sbom_out }}"
        fi

        if [ "${{ inputs.cmake_build_dir }}" != "" ]; then
          PARAM_CMAKE_BUILD_DIR="--cmake_dir ${{ inputs.cmake_build_dir }}"
        fi

        if [ "${{ inputs.msproj_file }}" != "" ]; then
          PARAM_MSPROJ="--msbuild_proj ${{ inputs.msproj_file }}"
        fi

        echo "Parameters: $PARAM_SBOM_OUT $PARAM_CMAKE_BUILD_DIR $PARAM_MSPROJ"
        poetry --project=sbom_tool run python3 sbom_tool/SbomEnrichment.py "${{ inputs.database }}" "${{ inputs.sbom }}" $PARAM_SBOM_OUT $PARAM_CMAKE_BUILD_DIR $PARAM_MSPROJ
